### ISSUE TITLE
Task mutes, not just volume==0

### ISSUE THREAD

**Issue by pgulley** [pgulley/gen_rep#7]
Right now we achieve a mute by just setting the volume to zero- but there should be a way to mute and leave the gain where it is- so, probably a second gain step that's controlled by a bool for each task.

**Comment by alissavoth** [comment]
That's a good idea. I would also like to be able to see if audio is still playing after the bank is turned off. Atm if you hit enter, all of the previous audio that was triggered continues to play, which I think is great. So then, if I use a very short loop frequency (eg. 5 seconds) and the bank has been triggering audio for the past minute, when I turn off the bank the audio will continue for a while. If I've muted this bank I won't know when the audio has finished, and so raising the volume later is kind of risky.

**Comment by pgulley** [comment]
just pushed a fix!
