### ISSUE TITLE
Task Status Indicators

### ISSUE THREAD

**Issue by pgulley** [pgulley/gen_rep#8]
That's a good idea. I would also like to be able to see if audio is still playing after the bank is turned off. Atm if you hit enter, all of the previous audio that was triggered continues to play, which I think is great. So then, if I use a very short loop frequency (eg. 5 seconds) and the bank has been triggering audio for the past minute, when I turn off the bank the audio will continue for a while. If I've muted this bank I won't know when the audio has finished, and so raising the volume later is kind of risky.

_Originally posted by @alissavoth in https://github.com/pgulley/gen_rep/issues/7#issuecomment-2209558389_

I'm thinking something like a color for the whole task associated with when it's playing? Should be very possible.

**Comment by pgulley** [comment]
Okay, implemented this- I changed a bunch of colors around to make this work in a way that I found pleasing and still functional! The "Is playing" status on the tasks gets updated exactly once per second- so there is a little bit of a delay visible sometimes

**Comment by pgulley** [comment]
scratch that, I think I fixed the delay

**Comment by alissavoth** [comment]
Hell yeah! It took me a minute to figure this out, but the color coding makes a lot of sense once you have a bunch of banks running.
