### ISSUE TITLE
Style to be responsive for various screens

### ISSUE THREAD

**Issue by pgulley** [pgulley/gen_rep#9]
Not sure if this is the place to comment, but the grid is too large to fit on my 13 inch laptop screen. I have to scroll around. Could the banks be smaller?

_Originally posted by @alissavoth in https://github.com/pgulley/gen_rep/issues/5#issuecomment-2209560409_
            
We can set the width of each task block to be based on the screen width percentage? But idk how to make all of the sub-components scale correctly- the spinner I think has to be hard-coded by pixel size? I'll investigate

**Comment by alissavoth** [comment]
Okay, thanks!

**Comment by pgulley** [comment]
Addressed in the commit above!
